"""create employee, employer, tax_information tables

Revision ID: 0827ca2ab2fb
Revises: a30f65c8054a
Create Date: 2024-04-27 13:41:55.025411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0827ca2ab2fb'
down_revision = 'a30f65c8054a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ssn', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.String(length=50), nullable=True),
    sa.Column('ein', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ein')
    )
    op.create_table('TaxInformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w2_form_id', sa.Integer(), nullable=False),
    sa.Column('federal_income_tax', sa.Float(), nullable=True),
    sa.Column('state_income_tax', sa.Float(), nullable=True),
    sa.Column('medicare_tax', sa.Float(), nullable=True),
    sa.Column('ss_tax', sa.Float(), nullable=True),
    sa.Column('medicare_wages', sa.Float(), nullable=True),
    sa.Column('ss_wages', sa.Float(), nullable=True),
    sa.Column('state_wages_tips', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['w2_form_id'], ['W2Form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('W2Form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Employer', ['employer_id'], ['id'])
        batch_op.create_foreign_key(None, 'Employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('W2Form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('employer_id')

    op.drop_table('TaxInformation')
    op.drop_table('Employer')
    op.drop_table('Employee')
    # ### end Alembic commands ###
