"""create auth token table

Revision ID: 6e81d080cf2e
Revises: 06713bcb7a53
Create Date: 2024-04-30 09:53:50.528867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e81d080cf2e'
down_revision = '06713bcb7a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuthToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AuthToken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuthToken_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthToken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuthToken_jti'))

    op.drop_table('AuthToken')
    # ### end Alembic commands ###
